# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: tbarret <tbarret@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/03/14 12:36:22 by tbarret           #+#    #+#              #
#    Updated: 2024/06/03 15:18:09 by tbarret          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRC = tests.cpp ./Class/Account.cpp
OBJ = ${SRC:.cpp=.o}
NAME = tests
HEADER = ./Class/Account.hpp
CC = c++
CFLAGS = -Wall -Wextra -Werror -std=c++98 
RM = rm -f

all: ${NAME}

%.o: %.cpp
	$(CC) ${CFLAGS} -c $< -o $@

${NAME}: ${OBJ}
	${CC} ${CFLAGS} ${OBJ} -o ${NAME}

clean:
	${RM} ${OBJ}

fclean: clean
	${RM} ${NAME}

re: fclean all

.PHONY : all clean fclean re
